### PR TITLE
major: Ios native port

### PR DESCRIPTION
**Pull request by Slesarew**
This is a major re-write of the app.

### Pure Rust backend

- All logic was moved to Rust native code; this includes key storage, transaction parsing, signing, history, etc.
- [sled](https://crates.io/crates/sled) is used as database engine
- metadata and networc specifications could be imported with fountain QR videos
- support message signing and legacy multiframe transactions
- cryptography imported directly from Substrate code

### iOS frontend

- iOS frontend written with modern SwiftUI framework
- QR scanner is multithreaded and thus works at rates of at least 30fps
- Seed phrases are stored with SecureEnclave
- General UI/UX changes to improve usability and simplify things

### Ethereum
is not supported anymore; to return support - either fork old RN branch or implement everything in pure Rust

### Legacy code

Almost nothing remains from version 4.5*

Most of Rust code is inherited from https://github.com/paritytech/parity-signer/tree/payload-parser-rust

## This PR would address the following issues:

#407
#318
#408
#758
#457
#713
#724
#736
#739
#767

### CODE REVIEW

**Comment by kirushik** [comment]
I'm OK with the general direciton of this — but am not currenlty available for a thorough code review of a  `+33,174 −32,944` pull request in a language I'm not too fluent with.
This only leaves me with an opportunity to do a sprt of QA/acceptance testing of the app itself — and this PR has no info on how I can get a pre-release version built from this branch for testing.

**Comment by Slesarew** [comment]
> how I can get a pre-release version built from this branch for testing.

That's what I meant really, I don't thing plowing through all this code is feasible now.

To build, first run
`./scripts/build.sh ios`
Then just build the workspace from ios directory in Xcode. It's already in the readme, but I'll need to improve that documentation further once this goes into more stable state.

**Comment by s3krit** [comment]
As an update to this; there is now a build available in TestFlight. Given an Apple ID, I can add whomever for QA/testing.

**Comment by TriplEight** [comment]
Please don't do such huge PRs, it's unreal to review it. 
Now, unfortunately, I do not have the iOS device for testing, but think it's worth getting one.

**Review by vas3k — APPROVED** [review]
Same as for #793: tested the last build from TestFlight: seed creation, metadata update, exporting, transaction parsing, transaction signing, extension integration

UI looks way better than in Android version but still need improvements

**Comment by blockchainunchained** [comment]
You absolute beast @Slesarew can I please buy you a beer?

**Comment by NukeManDan** [comment]
Congratulations on this @Slesarew 🍻

**Comment by kianenigma** [comment]
Congratulations! 🥂

**Comment by mcdonagg** [comment]
This is awesome, thank you for your hard work on this, how do I get my hands on it?

**Comment by Slesarew** [comment]
> This is awesome, thank you for your hard work on this, how do I get my hands on it?

There won't be ant app store releases until we are done with testing (and hopefully audits!), but it is really trivial to build (at your own risk, as usual, the frontend does not even *have* any tests as it is not in final state), you need rust and xcode or android studio depending on target. So, first it is `./scripts/build.sh ios`or `./scripts/build.sh android` and then open corresponding IDE and build. Android studio might need to be properly upgraded though and you'll need NDK obviously. And there is effectively no light color mode in android at the moment, as the Signer was always black, I've started with it - so switch to dark mode in the phone first.

**Pull request merged**
