### PR TITLE
chore: update splash screen

### PR DESCRIPTION
**Pull request by geastwood**
PR for #313 

Probably making it the background black is better.

Screenshot 2019-08-12 at 22 32 00

### CODE REVIEW

**Comment by geastwood** [comment]
[clabot:check]

**Comment by geastwood** [comment]
Updated the color.

**Comment by Tbaut** [comment]
Thanks a lot, I'll let @hanwencheng test on an iphone (I don't have a mac :)) before merging

**Comment by hanwencheng** [comment]
Tested on iOS devices. It all looks good, I just remove a duplicated image file in 54cf3a94d49c66691223dacd87c516d01c7c5ce2.

**Comment by geastwood** [comment]
Thanks for merging!

What value does it bring to introduce `react-native-splash-screen`?

**Comment by hanwencheng** [comment]
It hides the white react native bridging splash screen on both iOS and Android. 

Screenshot 2019-08-14 at 11 25 45

**Comment by geastwood** [comment]
The screenshot is only for development. And RN uses for iOS the *LaunchScreen* which is the essential way for implementing splash screen. Afaik, the lib makes sense when you want to show a splash screen programmatically, e.g. show an advertisement while the user is back to the app, namely hooking into the lifecycle of user interaction.

**Comment by hanwencheng** [comment]
Thanks for the explanation, we will ignore that screen then.

**Pull request merged**
