### PR TITLE
Make sure the recovery phrase is emptied upon process abortion

### PR DESCRIPTION
**Pull request by Tbaut**
- closes https://github.com/paritytech/parity-signer/issues/261(the second bug mentioned)

Users could set a seed for the `new` account in `AccountRecover`. This seed remained in the `AccountStore` state upon unmount. It needed to be manually removed in case a user doesn't finish the process.

### CODE REVIEW

**Comment by Tbaut** [comment]
Please give it a shot, it's a small one with big impact. You could end up with an empty account in the account list if you really wished.

**Comment by hanwencheng** [comment]
The PR LGTM, but one more thing about the workflow of recovering an account, since create a empty account will result in nothing in the storage, I think we should prevent the user enter the pin creation page with empty seed. also according to the [previous discussion](https://github.com/paritytech/parity-signer/issues/127#issuecomment-454610060), related code [here](https://github.com/paritytech/parity-signer/blob/master/src/util/account.js#L32-L47), basically these situation need to be prevented from further steps, probably we should create a new issue to solve this problem.

**Comment by Tbaut** [comment]
You're right, I'll take care of this in this PR, it shouldn't be a big deal. I'll separate the other small bugfix into its own PR.

**Comment by Tbaut** [comment]
On this PR is now as it should be, fixing one problem.

**Pull request merged**
