### PR TITLE
Additional account validation added

### LINKED ISSUE #127: No recovery words on Backup Account screen
screen shot 2018-08-06 at 13 23 46

### PR DESCRIPTION
**Pull request by fckt**
fixes #127

### CODE REVIEW

**Comment by ltfschoen** [comment]
I think it would help to disable the Next Step button by default and enable it in a different colour when all the input fields are valid.

I also think we should highlight what form fields still need to be completed before the Next Step button will be enabled.

**Comment by Tbaut** [comment]
We will not do a release for this fix. The release will be done for the next feature that we expect to have which is Bip39 support. This fix will not be included then.

**Comment by fckt** [comment]
> I think it would help to disable the Next Step button by default and enable it in a different colour when all the input fields are valid.
> 
> I also think we should highlight what form fields still need to be completed before the Next Step button will be enabled.

It's just a quick fix for the exact annoying problem. If it doesn't makes the app better - we can just leave it as it is and close this PR.

**Comment by ltfschoen** [comment]
I just tried these changes and they work great!

**Pull request merged**
