### PR TITLE
Bump React Native to 0.60.3 & bump react-navigation, keyboard, camera, native components.

### PR DESCRIPTION
**Pull request by yjkimjunior**

### CODE REVIEW

**Comment by yjkimjunior** [comment]
just realized `react-native-git-upgrade` is dead...going to have to be a tedious manual process 😭

**Comment by yjkimjunior** [comment]
Note: 
```
React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
  - react-native-camera (to unlink run: "react-native unlink react-native-camera")
  - react-native-secure-storage (to unlink run: "react-native unlink react-native-secure-storage")
  - react-native-vector-icons (to unlink run: "react-native unlink react-native-vector-icons")
```

**Comment by yjkimjunior** [comment]
Builds on Android. Going to have to test with iOS later after upgrading my Xcode.

**Comment by yjkimjunior** [comment]
https://github.com/facebook/react-native/issues/25601

**Comment by yjkimjunior** [comment]
@Tbaut at last, ready to test on android :)

**Comment by Tbaut** [comment]
Not sure if that's an issue but I had to downgrade `minSdkVersion` in `android/build.gradle` and `app/android/build.gradle` because my device sdk version is `25` which corresponds to android 7.1,  (also we need to go as low as possible because we are targeting potentially super old devices).

I get the following error (can't do a screenshot unfortunately):
>Invariant Violation: The navigation prop is missing for this navigator. In 
react-navigation 3 you must set up your app container directly. More info: 
https://reactnavigation.org/docs/en/app-containers.html

>located in Navigator (at createKeyboardAwareNavigator.js 12) 
in KeyboardAwareNavigator (at App.js 62)
...

**Comment by yjkimjunior** [comment]
this is how it works for me currently -> http://g.recordit.co/WKKrLpVbg1.gif

as a last sanity check, could you manually delete the index.android.bundle file in `parity-signer/android/app/assets` then run `react-native start --reset-cache` from `parity-signer` then refresh the app on your phone?  this should regenerate the bundle.

regarding your point on compatibility, I am looking into how low we can support right now

**Comment by yjkimjunior** [comment]
Ok, set minSdkVersion back to 16, tested on Nexus 5 (2013), and Pixel 2 (2017)

**Comment by Tbaut** [comment]
Got it running as well, taking a loot at the header style now

**Comment by yjkimjunior** [comment]
got it building on ios now 🎆

**Comment by yjkimjunior** [comment]
tested on ios -> http://g.recordit.co/Y530KKSNlW.gif

woop woop now i can get back to light ui :)

**Comment by yjkimjunior** [comment]
Tested on iOS -> https://kovan.etherscan.io/tx/0xdee4608ae5f3ec23411558941bc086f1fee793303eed95996194e1df76303cce

**Comment by Tbaut** [comment]
on Android https://kovan.etherscan.io/tx/0x9446dce4b9b32ac510897d115e7e6913a385c3fa75f6f513cfdae92f2e08454f

**Pull request merged**
