### PR TITLE
Bump jest to 24.8.0

### PR DESCRIPTION
**Pull request by Tbaut**
Self explanatory, and more sensible this time :)
Tested successfully the build and functionnalities on android.

### CODE REVIEW

**Comment by Tbaut** [comment]
Do you mean I should remove the `yarn.lock`? I've had the package-lock.json in [previous PRs](https://github.com/paritytech/parity-signer/pull/227/files)`

**Comment by yjkimjunior** [comment]
As long as it's consistent it should be no problem. Dug a little into past PR's where just the `yarn.lock` is committed. e.g. https://github.com/paritytech/parity-signer/pull/232/files

**Comment by maciejhirsz** [comment]
I don't have any strong feelings for or against yarn/npm, so adding whichever lock file on .gitignore and then using the other is fine with me. `npm` might be a bit easier since we can then remove `yarn` from required dependencies for the setup, but I reckon it isn't really a blocker for anyone.

**Comment by Tbaut** [comment]
I went for removing the yarn.lock and adding it to .gitignore,

**Comment by yjkimjunior** [comment]
ah I just realized the `setup_macos.sh` script actually runs yarn at the :/

I will change this to `npm install` in a separate PR

**Comment by fckt** [comment]
> I went for removing the yarn.lock and adding it to .gitignore,

Consider to read this:
https://yarnpkg.com/blog/2018/06/04/yarn-import-package-lock/

>> We highly recommend you to delete the package-lock.json file if you decide to use yarn in order to avoid future confusion and possible consistency issues.

**Pull request merged**
