### PR TITLE
fix: allow whitespaces in password

### PR DESCRIPTION
**Pull request by aegyed-91**
fixes https://github.com/paritytech/parity-signer/issues/721

### CODE REVIEW

**Review by Tbaut — CHANGES_REQUESTED** [review]
I don't think this is a particularly good practice here in a derivation path.

**Comment by aegyed-91** [comment]
If I am not mistaken `passwordRegex` is only being used for the passphrase, not for the derivation path.  

According to [subkey docs](https://substrate.dev/docs/en/knowledgebase/integrate/subkey#password-protected-keys), a passphrase with whitespaces is allowed.

**Comment by Tbaut** [comment]
This regex is used to validate or not the password of a validation path. I can't find in the link you gave any mention of passphrase, nor any mention of a password accepting whitespace. I'm not saying subkey doesn't support it, I didn't try.

**Comment by aegyed-91** [comment]
Ohh sorry, I might have confused you by interchangeably using password and passphrase. I am talking about the BIP39 Passphrase. If you check the subkey documentation I linked above more carefully, you can find plenty of examples involving password/passphrase with whitespaces. Let me quote it for you:

```bash
# generate keypair with a passphrase
subkey generate --password "pencil laptop kitchen cutter"
Secret phrase `nurse forest alert width radar series exit traffic fashion swing sign miracle` is account:
  Secret seed:      0xc7cc6e9589b6b28f5deb9dd4bba3fde62caf32116e21fae20c20327687c6838a
  Public key (hex): 0xf22ad8b59bf3b55b795b07758906ec95fff9b30050322da14e7fbf75b170d148
  Account ID:       0xf22ad8b59bf3b55b795b07758906ec95fff9b30050322da14e7fbf75b170d148
  SS58 Address:     5HYEB1MFnzWfQRyckrgYPpe5bDfh1jhsbG8aJZ8eXgygRzhL

# restore key from 12 word BIP 39 seed and passphrase
subkey inspect "nurse forest alert width radar series exit traffic fashion swing sign miracle///pencil laptop kitchen cutter"
Secret Key URI `nurse forest alert width radar series exit traffic fashion swing sign miracle///pencil laptop kitchen cutter` is account:
  Secret seed:      0xc7cc6e9589b6b28f5deb9dd4bba3fde62caf32116e21fae20c20327687c6838a
  Public key (hex): 0xf22ad8b59bf3b55b795b07758906ec95fff9b30050322da14e7fbf75b170d148
  Account ID:       0xf22ad8b59bf3b55b795b07758906ec95fff9b30050322da14e7fbf75b170d148
  SS58 Address:     5HYEB1MFnzWfQRyckrgYPpe5bDfh1jhsbG8aJZ8eXgygRzhL
```

**Comment by Tbaut** [comment]
This is called the mnemonic, or mnemonic seed mostly in the code, and consist of a suite of 12 to 24 words. It does contain white space, and the regex you changed in this PR does not relate to it.

**Comment by aegyed-91** [comment]
Nevermind, I'll build a custom .apk

**Pull request closed without merging**
