### PR TITLE
fix: Relates to #140. Update React Native to 0.56

### PR DESCRIPTION
**Pull request by ltfschoen**

### CODE REVIEW

**Comment by ltfschoen** [comment]
Updates have been made in branch 'luke-140-update-react-native-test' (ignore the "release" and "config" properties, and "commit-wizard" value, that appear to have been added automatically by a hook, but I first have to overcome this issue https://github.com/paritytech/parity-signer/issues/214 so that I know the updates aren't breaking the build or causing any device errors on Android. I'll also need help from someone else to confirm that it build and doesn't cause any device errors on an iPhone device

**Comment by ltfschoen** [comment]
I've only been able to update to react-native 0.56. Please kindly check if these changes also work on iOS. I've only tested that it builds and loads successfully on an Android Samsung Galaxy 8 Note.

I've attempted to further update to react-native 0.57.8 in this branch 'luke-140-update-react-native-rn-0.57.8-wip' but I got errors shown below:

<details><p><pre>
> Configure project :react-native-vector-icons 
WARNING: The option 'android.enableAapt2' is deprecated and should not be used anymore.
Use 'android.enableAapt2=true' to remove this warning.
It will be removed at the end of 2018.
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation'.
It will be removed at the end of 2018
WARNING: The specified Android SDK Build Tools version (26.0.1) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.0.
Android SDK Build Tools 27.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :react-native-camera:compileDebugJavaWithJavac FAILED
/Users/scon/code/src/paritytech/parity-signer/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/CameraModule.java:12: error: cannot find symbol
import com.facebook.react.uimanager.UIBlock;
                                   ^
  symbol:   class UIBlock
  location: package com.facebook.react.uimanager
/Users/scon/code/src/paritytech/parity-signer/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/CameraModule.java:216: error: cannot find symbol
        uiManager.addUIBlock(new UIBlock() {
                                 ^
  symbol:   class UIBlock
  location: class CameraModule
/Users/scon/code/src/paritytech/parity-signer/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/CameraModule.java:237: error: cannot find symbol
        uiManager.addUIBlock(new UIBlock() {
                                 ^
  symbol:   class UIBlock
  location: class CameraModule
/Users/scon/code/src/paritytech/parity-signer/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/CameraModule.java:259: error: cannot find symbol
    uiManager.addUIBlock(new UIBlock() {
                             ^
  symbol:   class UIBlock
  location: class CameraModule
/Users/scon/code/src/paritytech/parity-signer/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/CameraModule.java:282: error: cannot find symbol
      uiManager.addUIBlock(new UIBlock() {
                               ^
  symbol:   class UIBlock
  location: class CameraModule
/Users/scon/code/src/paritytech/parity-signer/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/CameraModule.java:305: error: cannot find symbol
      uiManager.addUIBlock(new UIBlock() {
                               ^
  symbol:   class UIBlock
  location: class CameraModule
/Users/scon/code/src/paritytech/parity-signer/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/CameraModule.java:326: error: cannot find symbol
      uiManager.addUIBlock(new UIBlock() {
                               ^
  symbol:   class UIBlock
  location: class CameraModule
/Users/scon/code/src/paritytech/parity-signer/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/CameraModule.java:352: error: cannot find symbol
        uiManager.addUIBlock(new UIBlock() {
                                 ^
  symbol:   class UIBlock
  location: class CameraModule
/Users/scon/code/src/paritytech/parity-signer/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/events/BarCodeReadEvent.java:37: error: method init in class Event<T> cannot be applied to given types;
    super.init(viewTag);
         ^
  required: int,long
  found: int
  reason: actual and formal argument lists differ in length
  where T is a type-variable:
    T extends Event declared in class Event
/Users/scon/code/src/paritytech/parity-signer/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/events/PictureTakenEvent.java:22: error: method init in class Event<T> cannot be applied to given types;
    event.init(viewTag);
         ^
  required: int,long
  found: int
  reason: actual and formal argument lists differ in length
  where T is a type-variable:
    T extends Event declared in class Event
/Users/scon/code/src/paritytech/parity-signer/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/events/BarcodeDetectionErrorEvent.java:29: error: method init in class Event<T> cannot be applied to given types;
    super.init(viewTag);
         ^
  required: int,long
  found: int
  reason: actual and formal argument lists differ in length
  where T is a type-variable:
    T extends Event declared in class Event
/Users/scon/code/src/paritytech/parity-signer/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/events/BarcodesDetectedEvent.java:40: error: method init in class Event<T> cannot be applied to given types;
    super.init(viewTag);
         ^
  required: int,long
  found: int
  reason: actual and formal argument lists differ in length
  where T is a type-variable:
    T extends Event declared in class Event
/Users/scon/code/src/paritytech/parity-signer/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/events/PictureSavedEvent.java:27: error: method init in class Event<T> cannot be applied to given types;
        super.init(viewTag);
             ^
  required: int,long
  found: int
  reason: actual and formal argument lists differ in length
  where T is a type-variable:
    T extends Event declared in class Event
/Users/scon/code/src/paritytech/parity-signer/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/events/CameraReadyEvent.java:22: error: method init in class Event<T> cannot be applied to given types;
    event.init(viewTag);
         ^
  required: int,long
  found: int
  reason: actual and formal argument lists differ in length
  where T is a type-variable:
    T extends Event declared in class Event
/Users/scon/code/src/paritytech/parity-signer/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/events/FaceDetectionErrorEvent.java:28: error: method init in class Event<T> cannot be applied to given types;
    super.init(viewTag);
         ^
  required: int,long
  found: int
  reason: actual and formal argument lists differ in length
  where T is a type-variable:
    T extends Event declared in class Event
/Users/scon/code/src/paritytech/parity-signer/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/events/CameraMountErrorEvent.java:27: error: method init in class Event<T> cannot be applied to given types;
    super.init(viewTag);
         ^
  required: int,long
  found: int
  reason: actual and formal argument lists differ in length
  where T is a type-variable:
    T extends Event declared in class Event
/Users/scon/code/src/paritytech/parity-signer/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/events/FacesDetectedEvent.java:50: error: method init in class Event<T> cannot be applied to given types;
    super.init(viewTag);
         ^
  required: int,long
  found: int
  reason: actual and formal argument lists differ in length
  where T is a type-variable:
    T extends Event declared in class Event
/Users/scon/code/src/paritytech/parity-signer/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/events/TextRecognizedEvent.java:55: error: method init in class Event<T> cannot be applied to given types;
    super.init(viewTag);
         ^
  required: int,long
  found: int
  reason: actual and formal argument lists differ in length
  where T is a type-variable:
    T extends Event declared in class Event
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/scon/code/src/paritytech/parity-signer/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/Camera2.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
18 errors


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-camera:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
41 actionable tasks: 1 executed, 40 up-to-date
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
</pre></p></details>

**Comment by ltfschoen** [comment]
> Why delete `.babelrc`?

Because in Babel 7 we use babel.config.js for project-wide configuration https://babeljs.io/docs/en/config-files, and this appears to be a project-wide configuration rather than a file-relative configuration (where you use .babelrc)

**Comment by fckt** [comment]
@maciejhirsz why merge? Does anybody tested it on iOS?

> I've only been able to update to react-native 0.56. Please kindly check if these changes also work on iOS. I've only tested that it builds and loads successfully on an Android Samsung Galaxy 8 Note.

**Comment by maciejhirsz** [comment]
Looks pretty innocuous to me, it's only touching JS VM parts. I'm hoping to test iOS builds with Thibo next week on hardware.

**Comment by fckt** [comment]
It's a major upgrade of `react-native`. The devil in the details: iOS JS VM (JavascriptCore) is a different one then Android's (V8). These tiny bits could break anything.

**Pull request merged**
