### PR TITLE
feat (#407): Dynamic network specs + metadata management

### PR DESCRIPTION
**Pull request by yjkimjunior**
In NetworkSettings, user should be able to view networks for which he/she has already the full networkSpec.

A network spec will remain the same as it currently is in `constants.js`

The calls-only metadata blob will be persisted with AsyncStorage. It will be keyed via networkKey, just like the network spec. So the networkKey, i.e. genesisHash is essentially just a primary key.

The separation is ideal as the metadata (I'd guesstimate most chains would have something averaging around 32kb) should only be queried at the point of completing the scanning and validation of a QR payload. Otherwise, it'd be very very slow.

This should also allow for easily building the HDKD refactor on top of without any big conflicts.

I will be up to whomever supplies the Network Spec QR payload to make sure it is well formatted. Which is where https://github.com/yjkimjunior/Substrate-Metadata-Qrs aims to mitigate friction. Particularly, the `identiconFn` supplied needs to meet the same format as https://github.com/polkadot-js/ui/blob/f2f36e2db07f5faec14ee43cf4295f5e8a6f3cfa/packages/reactnative-identicon/src/icons/Polkadot.tsx#L37

on the reading end:
* [x] - save the current metadata for Kusama, Substrate in `db`
* [x] - load the metadata from `db`, should be able to query it along with the rest of the `networkSpec`s
* [x] - button to scan metadata will pass that as a flag in props so that ScannerStore will know not to handle it as a regular message (in which case it would just hash it and try to sign it
* [x] - construct that Metadata from the concatenated blob
* [x] - register types
* [x] - PayloadDetails use the appropriate type registry depending on the `genesisHash` provided in the payload.
* [x] - Essentially all the Substrate stuff currently in `constants.js` will have to be moved to `db.js`. 
* currently we have a single type registry instance that is injected only once. There could be conflicts and overrwrites now with multiple networks, so need make sure to reset that each time a new payload is scanned.

On the generation end: https://metadata-qrs.herokuapp.com
* [x] - UI for easily getting a well formatted QR for Signer to be able to decode it. Input: ws endpoint. Output: QR. In between would call state_getMetadata, strip everything but calls from it, hex encode, then feed the result to @polkadot/react-qr.
* [x] - UI for browsing supported QRs.

### CODE REVIEW

**Comment by yjkimjunior** [comment]
main functionality works, need to rebase on HDKD branch

**Comment by hanwencheng** [comment]
would be happy to review it if conflicts solved.

**Comment by yjkimjunior** [comment]
i'll wrap up this weekend

**Comment by hanwencheng** [comment]
closed as included in #681

**Pull request closed without merging**
