### PR TITLE
fix: do not gobble up errors in bulks

### PR DESCRIPTION
**Pull request by montekki**
## Purpose

If one TX in the bulk is faulty or is not a Tranasction Signing action,
return just it.

### CODE REVIEW

**Review by prybalko — COMMENTED** [review]
I'm not following. If there are 100 transactions in a bulk and some of them are faulty, should we only return the first faulty one?

**Comment by montekki** [comment]
You are either good to sign ALL or app bails out. It should not happen so that the app silently errors on 1 tx out of 100, and gives you 99 signatures for those correct ones. That behavior could be really dangerous.

**Comment by prybalko** [comment]
Would make sense to show _all_ faulty transactions, not only the first one?

**Comment by montekki** [comment]
That is not that easy to do interface-wise and I would prefer to do a hotfix now and polish it after the release

**Review by prybalko — APPROVED** [review]

**Pull request merged**
