### PR TITLE
feat: Android export private key screens.

### PR DESCRIPTION
**Pull request by Dmitry-Borodin**
Made it possible to show preview and create separate screens.
Abstracted out navigation.
Updated and sorted dependencies.

Current UI flow is not final and disabled under the feature flag.

### CODE REVIEW

**Comment by montekki** [comment]
plz don't remove @tetekinandrey from reviewers and attach some UI previews to review as we do for iOS code

**Comment by Dmitry-Borodin** [comment]
@montekki There is no final UI in this PR, I will update it as I will integrate with backend in the next one.
But this one already have quite a lot of changed so I wanted to merge it just to avoid conflicts.

There are not changes since new parts are under feature flags and now shown.

**Comment by montekki** [comment]
There will be no conflicts, you are the only person working on android part currently. So maybe just finish the changes to commit a finished feature?

**Comment by Dmitry-Borodin** [comment]
Ok, hope nobody will make changes.

**Comment by montekki** [comment]
Why did you close this? Why not just add more changes here?

**Comment by krzys-bfi** [comment]
@Dmitry-Borodin if you are aiming for smaller PR, good tactic could be to just post PR with specific UI components that are finalised and would be used in designs for given screen. Then you can post screenshots / gifs / videos showcasing them, add previews / tests, etc and treat them as finalised ones.
Then the final PR with functionality is smaller and you can post PR and merge more often if that's what you are aiming for. You can check some of my recent PRs that follow that approach (design system components + their examples as separate PRs)
And no worries about having opened PR for couple of days and just updating it with `master`, it's really unlikely this will cause conflicts for you 👍

**Comment by Dmitry-Borodin** [comment]
@montekki when it's opened and people assigned,
So since I will continue with task in the same branch, I closed it and will open when it's done - just so you can review it only once and avoid unnecessary work.

And since it's my private branch, I will often rebase on master to keep git log nice, during review force pushes making it impossible to review only last changes, but when I'm in my private - I can keep log clean and nice.

**Comment by Dmitry-Borodin** [comment]
It was manly general changes to fix preview. Now I'm working on new components for this screen specifically.

**Pull request closed without merging**
