### PR TITLE
Rename terms-and-conditions.md.js to terms-and-conditions.md

### PR DESCRIPTION
**Pull request by sakshamtaneja21**

### CODE REVIEW

**Comment by Tbaut** [comment]
This must be a bot. I'll close for now :)

**Comment by sakshamtaneja21** [comment]
no not a bot 
i am a real person

**Comment by sakshamtaneja21** [comment]
clabot:check

**Comment by sakshamtaneja21** [comment]
ok

**Comment by sakshamtaneja21** [comment]
how can I get an invite of your GitHub organization as a member

**Pull request closed without merging**
