### PR TITLE
Proper lock on went into background

### PR DESCRIPTION
**Pull request by fckt**

### CODE REVIEW

**Comment by Tbaut** [comment]
It did not do the trick for me on android, I could take a screenshot and the screen of the app was visible on the "application overview".  (Signal just above is blank for instance).

image

**Comment by ligi** [comment]
to make it behave like signal there you need to do:

window.setFlags(FLAG_SECURE, FLAG_SECURE)

**Comment by Tbaut** [comment]
I couldn't manage to implement this fix in a timely manner. I messed up with the main Activity but couldn't make it compile. Any chance you can help with that @ligi :) ?

**Comment by tomusdrw** [comment]
@fckt what about ligi's suggestion?

**Comment by fckt** [comment]
> @fckt what about ligi's suggestion?

oh, I haven't tested on Android (due to lack of device). Sure, I'm going to do it now.

**Comment by fckt** [comment]
> @fckt what about ligi's suggestion?

Addressed

**Pull request merged**
