### PR TITLE
Security header refresh

### PR DESCRIPTION
**Pull request by Tbaut**
- closes https://github.com/paritytech/parity-signer/issues/266
- closes https://github.com/paritytech/parity-signer/issues/174

- "Secure" will never be shown again, as we can't be sure and it's a strong word.
- update to the new [RNCNetinfo api](https://github.com/react-native-community/react-native-netinfo#usage) (this removes a deprecation warning)
- get rid of SecurityStore and `unstated` shared state and consolidate the little logic in one screen
- remove another android permission that seems unneeded by NetInfo

Todo

- [x] Triple check that the removed permission doesn't affect how things work even on an apk. Done, built an apk and it launched and worked without trouble. :white_check_mark:

### CODE REVIEW

**Comment by hanwencheng** [comment]
out
Meet weird problem on iOS simulator, the state does not change when user click back.
I also set the breakpoint there and the listener is not called.

Need to be checked on real iOS device, probably is because simulator's problem

**Comment by hanwencheng** [comment]
ignore it since it is a [known issue](https://github.com/react-native-community/react-native-netinfo#issues-with-the-ios-simulator)

**Comment by yjkimjunior** [comment]
LGTM!

YljP3AEUYI

**Comment by Tbaut** [comment]
Real iPhone test successful by @yjkimjunior :)

**Pull request merged**
