### PR TITLE
[WIP] React and toolchain upgrade

### PR DESCRIPTION
**Pull request by fckt**
closes https://github.com/paritytech/parity-signer/issues/93, https://github.com/paritytech/parity-signer/issues/94

### CODE REVIEW

**Comment by debris** [comment]
I will try to build it now. Why was `ios/EthkeyBridge.swift` renamed to `ios/EthkeyBridge.1.swift` ?

**Comment by debris** [comment]
@fckt how do you build it on ios? I did:

```
rm -rf node_modules
rm -rf ios/DerivedData
yarn
open ios/NativeSigner.xcodeproj
Cmd+B
```

and it fails with:

```
Typedef redefinition with different types ('struct (anonymous struct at ../../react-native/React/Base/RCTBridgeModule.h:52:16)' vs 'struct RCTMethodInfo')
```

**Comment by fckt** [comment]
@debris https://github.com/debris/react-native-secure-storage/pull/2

**Comment by debris** [comment]
@fckt thanks!

I made 3 additional changes
- bumped `react-native-secure-storage` commit hash
- removed landscape support on iOS
- brought back support for iOS 8.0

I tested the project only in the simulator. Topbar and all views seems to be a bit fucked, but I guess it could be easily fixed by changing styles

**Pull request merged**
