### PR TITLE
feat: iOS: Display all derived keys from all networks on Key Details and allow for network filtering

### PR DESCRIPTION
**Pull request by krodak**
## Purpose
This PR aims to provide functionality of displaying all derived keys for given root key aand allow for network filtering.

## Scope
- use new API on Key Details to display data
- refactor Key Details logic to allow for reloading based on network selection

## TODOs
- [x] Display all keys based on `MKeysNew`
- [x] Update data model generation to be based on `MKeysNew`
- [x] Fix navigation to Public Key
- [x] Fix key export
- [x] Fix all modal actions
- [x] Allow for network filtering after selection
- [ ] Address any design review issues
- [ ] Align android to work with update API 

## Screenshots

| Light | Dark |
|-|-|
|||
|||
|||
|||
|||

### CODE REVIEW

**Comment by Dmitry-Borodin** [comment]
I've disabled broken code and it compiles, but usual old flow causing rust to crush - "io.parity.signer.uniffi.InternalException: called `Option::unwrap()` on a `None` value"
if any derived key is open.
Can't we just pass all keys in old API? Or it that intentional?
cc @montekki

**Review by Dmitry-Borodin — CHANGES_REQUESTED** [review]
1 need to test 2 things before this can be merged.
And one is old keys are broken probably on rust side.

**Comment by krodak** [comment]
@Dmitry-Borodin this error will be resolved if you update `details` sent when performing `.selectKey` navigation:

```
let details = "\($0.key.addressKey)\n\($0.network.networkSpecsKey)" // this is address key + new line + network specs key
let tapAction = .init(action: .selectKey, details: details)
```

**Comment by krodak** [comment]
@montekki I think some Rust needs also to be updated as clippy is failing 🙏🏻

**Comment by montekki** [comment]
@krodak @Dmitry-Borodin plz do not merge after you fix UI code; I will need to re-visit rust changes before merging

**Comment by Dmitry-Borodin** [comment]
@montekki in MKeys Can we pass MscNetworkInfo instead of MNetworkCard?
I don't have network info specs in non-redesigned screens.

**Comment by montekki** [comment]
@Dmitry-Borodin `MKeys` no longer exists, check the `udl` file

**Comment by Dmitry-Borodin** [comment]
@montekki I see you removed it today. So how should I hotfix that? Is there a good way? 
Small 3 lines description of where to get and where to pass which data would be much better than researching 50+ files plain text changelist.
This should be a hotfix,..

**Comment by montekki** [comment]
@Dmitry-Borodin `keys_by_seed_name`

**Comment by Dmitry-Borodin** [comment]
Btw I see we are using MKeysCard only in this MKeysNew, and it's a copy of MAddressCard but can be Swiped.
There is no swiping anymore, this functionality not used on android. I assume same for iOS, right @krodak  ?
I think we can remove MKeysCard completely as a model and just use MAddressCard instead. 
It's safe and very simple to change on Android.

**Comment by Dmitry-Borodin** [comment]
Android is fixed yet the question remains of how we should handle {REMOTE_KEYSET, BACKUP_KEYSET, EXPORT_MULTIPLE_KEYSETS } - for now it will just switch back, but there should be clear understandable logic to understand it won't miss often.

**Review by Dmitry-Borodin — APPROVED** [review]

**Comment by krodak** [comment]
@Dmitry-Borodin backup keys, export mutliple keys and export private keys are working as expected on iOS, you can check mentioned iOS build from TestFlight or changes within this PR 🙏🏻 Not sure what `REMOTE_KEYSET` refers to though

**Comment by krodak** [comment]
@Dmitry-Borodin that's not right, `MKeysCard` contains `addressKey` which we use for navigation, we can't switch to `MAddressCard`

**Comment by Dmitry-Borodin** [comment]
> MAddressCard

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct MAddressCard {
    pub base58: String,
    pub address_key: String,
    pub address: Address,
}

**Comment by Dmitry-Borodin** [comment]
> @Dmitry-Borodin that's not right, `MKeysCard` contains `addressKey` which we use for navigation, we can't switch to `MAddressCard`

@krodak 
`#[derive(Clone, Debug, PartialEq, Eq)]
pub struct MAddressCard {
    pub base58: String,
    pub address_key: String,
    pub address: Address,
}`

**Comment by krodak** [comment]
@Dmitry-Borodin my bad, I was looking on `master` branch 👍🏻

**Pull request merged**
