### PR TITLE
feat: Add Edgeware

### PR DESCRIPTION
**Pull request by carumusan**

### CODE REVIEW

**Comment by carumusan** [comment]
[clabot:check]

**Comment by carumusan** [comment]
Needs metadata support included. Think it's best worked on after the westend commit has been made as it contains useful refactorings.

**Comment by hanwencheng** [comment]
Thanks for the work and submitting the PR!

Meta data update info could be find [here](https://gist.github.com/hanwencheng/09b325c226fd44bf7ba5b99ba2e8e989). 

I would love to help merge it after typescript #521 and westend #541 PR.

**Comment by hanwencheng** [comment]
closes this one, integrate in #555.

**Pull request closed without merging**
